# Common options
source: .
destination: generated_content # or . or ~/MyProject or generated_content

# Asciidoc and attributes options
backend: html5
attributes:
   source-highlighter: coderay
   linkcss!: true
   data-uri: true

# Hyla options
# Generate command
#rendering: toc2adoc
rendering: adoc2html

# New/Create command
artefact_type: article
type: asciidoc

# Styles supported : liberation, asciidoctor, colony, foundation, foundation-lime, foundation-potion, github, golo, iconic, maker, readthedocs, riak, rocket-panda, rubygems
style: liberation

# Location of the Table of Content to be processed
# as a collection of asciidoc files
project_name: my-project
toc: /Users/chmoulli/MyProjects/hyla/data/toc.adoc # Change location

email_attributes:
  from:     "Charles Moulliard <ch007m@gmail.com>"
  to:       'cmoulliard@apache.org'
  subject:  "This is a beautiful HTML document created by Asciidoctor and Hyla Tool"

  # GMAIL 
  smtp_server:      'smtp.gmail.com'
  port:             '587'
  enable_starttls:  'true'
  user:             'xxx' 
  password:         'xxxx'

location: ./generated_content
file: asciidoc_book.html